Repository jv-farias/frontend-day-app, pull requests merged in 2023-10, with the labels that each got.

#34 Background Color
  css/style.css
Labels: Bug

#47 Logo readme
  README.md
  css/ao-vivo.css
  css/style.css
  html/index.html
Labels: Documentação

#50 Disable Enter Key for Search
  README.md
  ao-vivo.html
  node_modules/.package-lock.json
  package-lock.json
  public/css/ao-vivo.css
  src/cards-aovivo.ts
  src/main.js
  src/navigation-mobile.js
  src/templateAoVivo.js
Labels: Bug, Aprimoramento

#53 Fix Search Bar
  README.md
  src/atualizarCards.js
  src/main.js
  src/templateAoVivo.js
Labels: Bug

#56 Local Storage
  ao-vivo.html
  package.json
  public/css/ao-vivo.css
  src/Components.js
  src/Data.js
  src/LocalStorage.js
  src/Utils.js
  src/api.types.ts
  src/cards-aovivo.ts
  src/cards.js
  src/cards.types.ts
  src/colaboradores.ts
  src/dadosAoVivo.js
  src/dadosComunidades.js
  src/dadosConvida.js
  src/dadosFrontEnd.js
  src/main.js
  src/navigation-mobile.js
  src/search.js
  src/templateAoVivo.js
  src/templateComunidades.js
  src/templateConvida.js
  src/templateFrontEnd.js
Labels: Aprimoramento

#72 Fix hour data
  src/Data.js
Labels: Bug

#73 Resolvendo problemas de falta de links e footer quebrado.
  config-save.html
  index.html
  public/css/ao-vivo.css
  public/css/config-save.css
  src/Components.js
Labels: Bug, Aprimoramento
